name: plant_doctor_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # قاعدة البيانات والتخزين
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3

  # وسائط وواجهة
  lottie: ^3.1.2
  cupertino_icons: ^1.0.8

  # الكاميرا والصور
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  image: ^4.2.0

  # الذكاء الاصطناعي
  tflite_flutter: ^0.11.0

  # تعدد اللغات
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # أيقونة التطبيق
  flutter_launcher_icons: ^0.13.1

  # splash screen
  flutter_native_splash: ^2.4.0

# flutter native splash settings
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/splash.png
  
  color_dark: "#121212"
  image_dark: assets/icon/splash.png

  android_12:
    image: assets/icon/splash.png
    color: "#FFFFFF"
    color_dark: "#121212"
    # أندرويد 12 لا يقبل Padding برمجي، يعتمد كلياً على حجم الصورة نفسها
    
  fullscreen: true
  android: true
  ios: true

# إعدادات أيقونة التطبيق
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_app.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/
    - assets/lottie/
    - assets/category_icons/
    - assets/plants/
    - assets/pepper/
    - assets/potato/
    - assets/tomato/
    - assets/grape/
    - assets/database/plant_doctorv4.db
    - assets/labels.txt
    - assets/model/plant_disease.tflite

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
